name: silah
description: A matrimony and classifieds Flutter app (Silah).
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  # Firebase
  firebase_core: ^2.24.0
  firebase_messaging: ^14.7.0
  # Notifications
  flutter_local_notifications: ^17.2.3
  # HTTP & Storage
  dio: ^5.4.0
  shared_preferences: ^2.2.2
  # Google Sign-In
  google_sign_in: ^6.1.6
  # Image Picker
  image_picker: ^1.0.7
  # Socket.io
  socket_io_client: ^2.0.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/images/
    - assets/icons/
    - assets/logos/
